// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Videoteka.Data;

#nullable disable

namespace Videoteka.Migrations
{
    [DbContext(typeof(VideotekaDbContext))]
    [Migration("20230209154707_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Videoteka.Models.Domain.Clan", b =>
                {
                    b.Property<int>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClanId"));

                    b.Property<string>("BrojTelClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumClanarine")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailClana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KucniBrClana")
                        .HasColumnType("int");

                    b.Property<int>("PosKod")
                        .HasColumnType("int");

                    b.Property<string>("PrezimeClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrijavljenDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("UlicaClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClanId");

                    b.ToTable("Clanovi");
                });

            modelBuilder.Entity("Videoteka.Models.Domain.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaId"));

                    b.Property<string>("NazivKategorije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategorijaId");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("Videoteka.Models.Domain.Proizvod", b =>
                {
                    b.Property<int>("ProizvodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodId"));

                    b.Property<DateTime>("DatumDolaskaWeb")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumIzlaska")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direktor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Glumci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeProizvoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategorijaProizvoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KodProizvoda")
                        .HasColumnType("float");

                    b.Property<string>("OpisProizvoda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProizvodId");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("Videoteka.Models.Domain.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaposlenikId"));

                    b.Property<string>("BrojTelZaposlenika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailZaposlenika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeZaposlenika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PlacaZaposlenika")
                        .HasColumnType("bigint");

                    b.Property<string>("PozicijaZaposlenika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeZaposlenika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZaposlenikId");

                    b.ToTable("Zaposlenici");
                });
#pragma warning restore 612, 618
        }
    }
}
