// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Videoteka.Data;

#nullable disable

namespace Videoteka.Migrations
{
    [DbContext(typeof(VideotekaDbContext))]
    partial class VideotekaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Videoteka.Models.Domain.Clan", b =>
                {
                    b.Property<int>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClanId"));

                    b.Property<string>("BrojTelClana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumClanarine")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailClana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KucniBrClana")
                        .HasColumnType("int");

                    b.Property<string>("PosKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrijavljenDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("UlicaClana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClanId");

                    b.ToTable("Clanovi");
                });

            modelBuilder.Entity("Videoteka.Models.Domain.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaposlenikId"));

                    b.Property<string>("BrojTelZaposlenika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailZaposlenika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeZaposlenika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PlacaZaposlenika")
                        .HasColumnType("bigint");

                    b.Property<string>("PozicijaZaposlenika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeZaposlenika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZaposlenikId");

                    b.ToTable("Zaposlenici");
                });
#pragma warning restore 612, 618
        }
    }
}
